### PR TITLE
Drawer Refactor

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX

#### Changes proposed in this Pull Request:
- Refactor the Drawer component
- Allow Drawer to be built declaratively
- Simplify Types and Inheritance
- Update docs

### CODE REVIEW

**Comment by daileytj** [comment]
Simulator Screen Shot - iPhone 11 - 2021-02-10 at 08 12 43
[Screenshot of storybook drawer full config]
The chevron prop is not working properly anymore.

**Review by daileytj — APPROVED** [review]

**Comment by emclaug2** [comment]
Only thing I've noticed so far was a lack of animation when opening/closing nested nav items; was this something that we had before or was this accidently removed?

**Comment by emclaug2** [comment]
Looks good to me!  Just see comment above.

**Review by emclaug2 — APPROVED** [review]

**Review by emclaug2 — CHANGES_REQUESTED** [review]
Just noticed some bad rendering logic in the readme: 

https://github.com/pxblue/react-native-component-library/blob/feature/drawer-refactor/docs/Drawer.md

Some of the tables don't render correctly.

**Comment by joebochill** [comment]
> Only thing I've noticed so far was a lack of animation when opening/closing nested nav items; was this something that we had before or was this accidently removed?

This is due to a bug in the react-native-collapsible library where the initial height is incorrectly calculated when first rendering the drawer (and trying to open to the current active item). 

I posed two options: 1) swap out the collapsible for a regular view (we lose the animation, but the initial expansion works correctly — this is what is currently implemented), or 2) Keep the collapsible, but disable the automatic expanding to the selected item on first load.

I'm happy to switch to number 2 if there is consensus for that approach.

**Comment by emclaug2** [comment]
> > Only thing I've noticed so far was a lack of animation when opening/closing nested nav items; was this something that we had before or was this accidently removed?
> 
> This is due to a bug in the react-native-collapsible library where the initial height is incorrectly calculated when first rendering the drawer (and trying to open to the current active item). Part of the tree was getting cut off (including the currently selected item) and you have to collapse and re-expand the panel for it to recalculate the height correctly.
> 
> I posed two options: 1) swap out the collapsible for a regular view (we lose the animation, but the initial expansion works correctly — this is what is currently implemented), or 2) Keep the collapsible, but disable the automatic expanding to the selected item on first load.
> 
> I'm happy to switch to number 2 if there is consensus for that approach.

Would solution no 2 fix the animation?

**Comment by joebochill** [comment]
> Would solution no 2 fix the animation?

Yes, you would get the animated open/close effect, but the drawer would start with all items collapsed (instead of auto-expanding any parents of the active item).

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
