### PR TITLE
Implement the full CollapsibleHeaderLayout

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX

#### Changes proposed in this Pull Request:
- Enhance the Header component to manage 'dynamic' or 'static' variants
- Implement the CollapsibleHeaderLayout component which manages the spacing and scrolling of the main screen contents
- Update the docs / storybook
- Did some linting cleanup on hooks/dependencies

#### Screenshots:
collapsibleHeaderLayout

#### To Test:
- Swap the outer View component in the Showcase App.tsx with CollapsibleHeaderLayout
- Take the props from the existing Header and pass them into the `HeaderProps` prop of the CollapsibleHeaderLayout
- Remove the existing Header component
- Explore

> I have not checked this on Android yet, so that would be as good a place to start as any.

Alternatively, you can use the version of App.tsx I will share on Teams which does the above for you.
- The two menu buttons in the actionItems will swap the variant (first) and update the expanded/collapsed heights (second) if you want to test those out.

Make sure to poke around with all of the different combinations of things you can do (scrolled down, scrolled up, expanding and collapsing on click, opening and closing search in different locations, changing the sizes, changing the variant, etc.).

### CODE REVIEW

**Comment by jeffvg** [comment]
noticed some difference between android/iOS using the expanded prop. On android when expanded is set it scrolls to collapse and on iOS it does not. iOS stays extended...

image

**Comment by joebochill** [comment]
Are you talking about the `startExpanded` prop? 

That only comes into play the very first time the app is loaded to initialize some state variables. If you simply hot reload the app (e.g., by changing a property in App.tsx) it will (should?) have no effect unless you _reload_ the app on the device.

`startExpanded` also works independently of the `variant` prop. You can have a 'dynamic' header that starts expanded or you can have a `static` header that starts expanded. 

I suspect you may have been playing with the variant on one of your simulators (and ended up where one is dynamic and one is expanded) and then you set the `startExpanded` prop and refreshed the apps.

**Comment by jeffvg** [comment]
> Are you talking about the `startExpanded` prop?
> 
> That only comes into play the very first time the app is loaded to initialize some state variables. If you simply hot reload the app (e.g., by changing a property in App.tsx) it will (should?) have no effect unless you _reload_ the app on the device.
> 
> `startExpanded` also works independently of the `variant` prop. You can have a 'dynamic' header that starts expanded or you can have a 'static' header that starts expanded.
> 
> I suspect you may have been playing with the variant on one of your simulators (and ended up where one is dynamic and one is expanded) and then you set the `startExpanded` prop and refreshed the apps.

yes ok all good, it works

**Review by jeffvg — APPROVED** [review]
looks good on android and ios

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
