### PR TITLE
Update Storybook Defaults

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-1543 .

#### Changes proposed in this Pull Request:
- Update storybook story default states to match React web
- Couple of tweaks to fix issues in components

> Note, this was just for the story to update the default states of the stories. I noticed a couple of places where some knobs were not working or some component props were not working as expected. If we run into these, lets capture them as separate issues.

### CODE REVIEW

**Comment by jeffvg** [comment]
wondering 😕  if anyone got this branch running on android

**Comment by daileytj** [comment]
> wondering 😕 if anyone got this branch running on android

Working fine on android for me. I'm using the Pixel 4 API 29 emulator.

**Comment by huayunh** [comment]
From your demo today
image

* more_vert should always be the right most icon (especially when you have more than 1 action item)
* padding of the list items in the body content

**Comment by huayunh** [comment]
(Don't forget to change the font-weight in the scorecard body content)

**Comment by joebochill** [comment]
> (Don't forget to change the font-weight in the scorecard body content)

Which one? They should all be using body1 right now.

**Comment by huayunh** [comment]
From Figma: 
image
Notice the font weight change

**Comment by huayunh** [comment]
And spacing between icon and text

**Comment by daileytj** [comment]
simulator_screenshot_B225EFF7-118E-4111-BC44-1A381117A144
Super minor... but, what's going on with the icon for the "Schedule" navItem? We're using this same icon in react but it doesn't really seem appropriate.

**Comment by joebochill** [comment]
> Super minor... but, what's going on with the icon for the "Schedule" navItem? We're using this same icon in react but it doesn't really seem appropriate.

I saw that too...kinda weird, but I just copied what React is doing.

**Comment by joebochill** [comment]
Updated the icon and made a PR in react to match as well.

**Review by daileytj — APPROVED** [review]

**Comment by emclaug2** [comment]
Should the NavGroup 1 and NavGroup 2 in the picture Tom posted be all capitalized?  Just so it matches the other examples.   Otherwise looks good!

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
