### PR TITLE
Update intellisense documentation comments

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-2251

#### Changes proposed in this Pull Request:
- Add intellisense comments where missing for
    - components
    - props
    - functions
- Update existing intellisense comments where needed to match more closely with docs
- Update some docs to be more consistent

#### Screenshots:
image

#### To Test:
- clone the repository
- `yarn link:components`
- Open the App.tsx file and start typing out some components.
    - When you are getting hints for a component, you will see the detailed description
    - When typing out prop names, you will see detailed descriptions for the props

### CODE REVIEW

**Comment by huayunh** [comment]
I think you can insert links to our storybook too. Those JSDocs follow markdown syntax.

**Comment by joebochill** [comment]
> I think you can insert links to our storybook too. Those JSDocs follow markdown syntax.

We _can_ do that. The caveat is that our storybook always documents the latest version of the components. So if someone is getting intellisense pop ups from an older version of the library, they could be pointed to documentation that is not accurate for the version of the library they are using.

**Comment by joebochill** [comment]
But I suppose that's true for anyone who comes and reads our documentation at any time anyway. I went ahead and added some links to the docs.

**Review by huayunh — APPROVED** [review]
Can verify that it works through storybook.

**Pull request merged**
