### PR TITLE
Update to use react-native-paper v4

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX

#### Changes proposed in this Pull Request:
- Update lots of dependencies
- Upgrade to RNP version 4 & perform some migration tasks based on changes
- Address some linting and typescript issues
- Update the showcase to RNP 4 and fix some styling issues

> Available for testing as @pxblue/react-native-components@4.0.0-beta.2

### CODE REVIEW

**Comment by joebochill** [comment]
In part of my exploration to fix some typescript issues, I did update the tsconfig to build our library to esnext standards instead of es2015. This _might_ have some issues working with Jest out of the box (we can drop it back down if we need to).

**Comment by joebochill** [comment]
I dropped us back down to building in commonjs format since that appears to be the recommended approach for most packages and doesn't cause problems with jest in testing.

**Comment by huayunh** [comment]
I used pxb cli to generate a new rn project, yarn upgraded to the latest beta version of this component library, do nothing else, and the entire thing runs OK. 

Then I added the code snippet for empty states [as it is on Storybook](https://pxblue-components.github.io/react-native-dev/?path=/info/components-documentation--empty-state) then it screams at me for not having `react-native-safe-area-context` installed anywhere. 

Then I `yarn add react-native-safe-area-context`, which gives me version `^3.1.9`

Then I reload the code again. 

image

**Comment by huayunh** [comment]
Here are the commands I used in the review: 
```shell
npx -p @pxblue/cli@beta pxb new react-native --name=rntest --cli rnc --lint --language ts --prettier
cd rntest/
yarn upgrade @pxblue/react-native-components@4.0.0-beta.2
yarn android
// add in the empty states
// began to see errors in the console
yarn add react-native-safe-area-context
// saw more errors, so quit the terminal / console and reload
yarn android
```

**Comment by joebochill** [comment]
This looks like it is an issue with the project created by the CLI. It is not configured to use svg icons out of the box. You can verify this by testing with the 'latest' 3.x version of the components...the issue is present there as well.

If you use a component without icons (like ILI) it should work fine.

I've logged a new issue to update the CLI to include the svg icon setup (https://github.com/pxblue/pxblue-cli/issues/47)

**Comment by joebochill** [comment]
Confirmed: if you follow the steps in the react-native-svg-transformer readme to get it set up, the snippet works as expected:
image

**Review by huayunh — APPROVED** [review]
Demo project spins on Android emulator with no problem

**Pull request merged**
