### PR TITLE
Feature/2666 rebrand blui major 1

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # PXBLUE-2666

#### Changes proposed in this Pull Request:
- pxblue ==> brightlayer-ui

### CODE REVIEW

**Review by daileytj — CHANGES_REQUESTED** [review]
Please update the following:

- [x] Remove "Power Xpert Blue" from `LICENSE` file
- [x] Remove "Power Expert Blue" from `demos/api/stories/welcome.stories.tsx` file
- [ ] Replace `@pxblue` references for the storybook/api demo projects (correct me if this is out of scope for this story, but I think we should be updating the storybook and API docs to match this one. Don't worry about the showcase demo as that is a different beast.)

**Comment by bkarambe** [comment]
> Please update the following:
> 
> * [x]  Remove "Power Xpert Blue" from `LICENSE` file
> * [x]  Remove "Power Expert Blue" from `demos/api/stories/welcome.stories.tsx` file
> * [ ]  Replace `@pxblue` references for the storybook/api demo projects (correct me if this is out of scope for this story, but I think we should be updating the storybook and API docs to match this one. Don't worry about the showcase demo as that is a different beast.)

I think we should wait for publishing the beta version of comp library and then rebrand demos

**Comment by emclaug2** [comment]
I'm going to say since this is the major-1 version & the demos here aren't deployed anywhere, I don't think it should be required to convert them over to BLUI.  As long as the library builds & the code visually looks like it's been migrated over correctly we can skip the demos. @daileytj  thoughts?

**Comment by daileytj** [comment]
> I'm going to say since this is the major-1 version & the demos here aren't deployed anywhere, I don't think it should be required to convert them over to BLUI. As long as the library builds & the code visually looks like it's been migrated over correctly we can skip the demos. @daileytj thoughts?

That's fine. I'm mostly concerned about maintaining the ability to locally test bug fixes should we need to fix something in this version. I'm happy to move this along though.

**Review by daileytj — APPROVED** [review]
If we're cool with the storybook not being migrated with the n-1 conversion then this is good to go.

**Comment by emclaug2** [comment]
@bkarambe @daileytj I've thought about this a little more & think it'd be a good idea to update the storybook stories. 
I've published a beta package @ 5.4.1-beta.0;  I just want to be sure they integrate into a project without issues.

@bkarambe Before merging this in can you update the storybook stories to use the beta package?

**Review by daileytj — CHANGES_REQUESTED** [review]
Blocking this until the storybook is updated

**Comment by jeffvg** [comment]
noticed this error while running storybook for safe area provider on collapsible header layout and header story
image

**Comment by jeffvg** [comment]
also noticed some styling issues on score card

image

**Comment by bkarambe** [comment]
> also noticed some styling issues on score card
> 
> image

I think this issue is there in the base release branch and need to be addressed separately.

**Comment by bkarambe** [comment]
> noticed this error while running storybook for safe area provider on collapsible header layout, header and user menu image

Same for this, this issue is there in the base release branch and need to be addressed separately.

**Comment by emclaug2** [comment]
For the scorecard looking weird in storybook, if it's in already in the v5.x.x release version, I'm thinking it's okay to skip it but could you log an issue for these @bkarambe?  However, there's a good chance both these issues won't get fixed, since this is already for an older version of the comp library.

**Comment by bkarambe** [comment]
A bug has been logged for the findings https://github.com/pxblue/react-native-component-library/issues/231

**Pull request merged**
