### PR TITLE
and step for PR & jest coverage collection

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- add codecov yml
- set jest config coverage and collection
- remove codecov script that is deprecated

image

### CODE REVIEW

**Review by joebochill — APPROVED** [review]
Looks good...just have that question about the 70...100 mentioned in the other PR.

**Comment by jeffvg** [comment]
> Looks good...just have that question about the 70...100 mentioned in the other PR.

image

**Comment by jeffvg** [comment]
> Looks good...just have that question about the 70...100 mentioned in the other PR.

we can adjust this later but this is the default config for most. 
Would it be better if we use range 50...75

**Comment by joebochill** [comment]
Okay, no that's cool. As long as we're still seeing coverage values that are less than 70, I'm not too concerned about the colors.

**Pull request merged**
