### PR TITLE
Re-scaffold storybook

### PR DESCRIPTION
**Pull request by joebochill**
Changes proposed in this Pull Request:
- Re-scaffold the storybook demo
- Configure to work with latest xCode
- Use PX Blue CLI for scaffold creation

### CODE REVIEW

**Comment by emclaug2** [comment]
This worked locally on my machine but is failing in circle ci.  If you fix the build-storybook stage I'll approve it.

**Comment by jeffvg** [comment]
Should storybook or showcase fire up?

**Comment by joebochill** [comment]
Storybook and showcase should both work now.
You'll get an error on the eslint-config package until we publish the 2.0.0 version (currently in beta waiting for PR review)

**Comment by emclaug2** [comment]
> Storybook and showcase should both work now.
> You'll get an error on the eslint-config package until we publish the 2.0.0 version (currently in beta waiting for PR review). You can swap ^2.0.0 for 2.0.0-beta.2 to verify

I approved the other PR, will merge this in whenever the new package is published.

**Pull request merged**
