### PR TITLE
fix icon switch

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .
updated the code for icon switch

#### Changes proposed in this Pull Request:
- 
- 
- 

#### Screenshots / Screen Recording (if applicable)
-

#### To Test:
- 

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Comment by ektaghag-eaton** [comment]
Can we fix prettier and test cases?

**Review by ektaghag-eaton — COMMENTED** [review]
Did we test this changes in RN docs?

**Comment by ArshdeepSingh3-eaton** [comment]
> Did we test this changes in RN docs?

yes
it works in RN Docs

**Comment by ArshdeepSingh3-eaton** [comment]
https://github.com/user-attachments/assets/7df82652-31bd-4e56-98fb-9284e8e631f4

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
